# Generated by Django 4.1.4 on 2022-12-30 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('Vente', 'Vente'), ('Echange', 'Échange'), ('Location', 'Location'), ('Location pour vacances', 'Location pour vacances')], default='Vente', max_length=25)),
                ('type', models.CharField(max_length=30)),
                ('surface', models.FloatField(max_length=30)),
                ('description', models.TextField()),
                ('prix', models.FloatField(max_length=30)),
                ('wilaya', models.CharField(max_length=25)),
                ('commune', models.CharField(max_length=25)),
                ('addresse', models.CharField(max_length=40)),
                ('date_pub', models.DateField(auto_now_add=True)),
                ('annonceur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='annonces/')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.annonce')),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.annonce')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresse', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=15)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
