# Generated by Django 4.1.4 on 2022-12-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annonce',
            options={'ordering': ['date_pub']},
        ),
    ]
