# Generated by Django 4.1.4 on 2022-12-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_alter_annonce_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annonce',
            options={'ordering': ['-date_pub']},
        ),
    ]
