# Generated by Django 4.1.4 on 2022-12-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_alter_annonce_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
