# Generated by Django 4.1.4 on 2022-12-31 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realestate', '0004_alter_annonce_date_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to=settings.AUTH_USER_MODEL),
        ),
    ]
