# Generated by Django 4.1.4 on 2023-01-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0007_alter_contact_utilisateur_alter_photo_annonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='prix',
            field=models.CharField(max_length=30),
        ),
    ]
