# Generated by Django 4.1.4 on 2023-01-07 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0008_alter_annonce_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='annonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.annonce'),
        ),
    ]
