# Generated by Django 4.1.4 on 2023-01-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0010_alter_annonce_annonceur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='date_pub',
            field=models.DateField(auto_now_add=True),
        ),
    ]
