# Generated by Django 4.1.4 on 2023-01-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0011_alter_annonce_date_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
