# Generated by Django 4.1.4 on 2023-01-13 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0013_alter_annonce_date_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='annonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='realestate.annonce'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='annonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='realestate.annonce'),
        ),
    ]
