# Generated by Django 4.1.4 on 2023-01-13 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0014_alter_offre_annonce_alter_photo_annonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='annonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.annonce'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='annonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.annonce'),
        ),
    ]
