# Generated by Django 4.1.4 on 2023-01-31 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0017_alter_offre_annonce_alter_photo_annonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='annonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='realestate.annonce'),
        ),
    ]
