# Generated by Django 4.1.4 on 2023-01-31 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0018_alter_offre_annonce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonce',
            old_name='annonceur',
            new_name='utilisateur',
        ),
    ]
