# Generated by Django 4.1.4 on 2023-01-31 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0019_rename_annonceur_annonce_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='annonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='realestate.annonce'),
        ),
    ]
